g151210045-odev3/HamzaProje/Controllers/yanSayfalarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HamzaProje.Controllers
{
    public class yanSayfalarController : Controller
    {
        // GET: yanSayfalar
        public ActionResult Haberler()
        {
            return View();
        }
        public ActionResult Duyurular()
        {
            return View();
        }
        public ActionResult Galeri()
        {
            return View();
        }
        public ActionResult dersSaatlerimiz()
        {
            return View();
        }
        public ActionResult Urunler()
        {
            return View();
        }

    }
}

g151210045-odev3/HamzaProje/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hamza Spor", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ana Sayfa", "Index", "Home")</li>
                    <li>@Html.ActionLink("Hakkımızda", "About", "Home")</li>
                    <li>@Html.ActionLink("Ürünlerimiz", "Urunler", "yanSayfalar")</li>
                    <li>@Html.ActionLink("İletişim", "Contact", "Home")</li>
                </ul>
                <div class="nav navbar-nav navbar-right col-md-4">
                    <div class="col-md-3" style="margin-top:8px;">
                        <div class="dropdown">
                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">TR <span class="caret"></span></button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <li><a href="#">EN</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-9" style="margin-top:8px;">
                        <div class="input-group">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">Ara</button>
                            </span>
                            <input type="text" class="form-control" placeholder="Arama...">
                        </div>
                    </div>
                </div>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <footer>
            <div>
                <div class="panel-body"style="background-color:thistle">
                    <b style="margin:0;">&copy;Copyrighted Hamza Spor</b>
                    <div style="float: right" >
                        <a href="https://www.facebook.com/">
                            <img src="~/Content/images/Facebook.jpg" width="40" height="40">
                        </a>
                        <a href="https://twitter.com/">
                            <img src="~/Content/images/Twitter.png" width="40" height="40">
                        </a>
                        <a href="https://youtube.com/">
                            <img src="~/Content/images/Youtube.png" width="40" height="40">
                        </a>
                        </div>
                    </div>
            </div>
        </footer>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>